#define SWI_PRINTF 1
#define SWI_YIELD 2
#define SWI_SET_GPIO_IN 3
#define SWI_SET_GPIO_OUT 4
#define SWI_SET_GPIO_VALUE 5
#define SWI_MCP23S18_REGISTER 6
#define SWI_MCP23S18_GET_ACTIVE_PINS 7
#define SWI_MCP23S18_ACTIVATE_PIN 8
#define SWI_MCP23S18_CONFIGURE_PIN 9

